export const PRELOADED_LISTS = {
  english_basic: [
    "planet",
    "apollo",
    "lunar",
    "solar",
    "orbit",
    "comet",
    "meteor",
    "rocket",
  ],
  hebrew_sample: ["שלום", "חלום", "עולם", "מלך", "יום", "לילה"],
  hebrew_figures: [
    "ישוע",
    "יהוה",
    "רוחהקודש",
    "פטרוס",
    "יוחנן",
    "יעקב",
    "מרים",
    "מיכאל",
    "גבריאל",
    "רפאל",
    "אברהם",
    "משה",
    "דוד",
    "שרפים",
  ],
  hebrew_library: [
    "ישוע",
    "יהוה",
    "משיח",
    "רוחהקודש",
    "מרים",
    "יוסף",
    "פטרוס",
    "יוחנן",
    "יעקב",
    "מיכאל",
    "גבריאל",
    "רפאל",
    "אברהם",
    "יצחק",
    "משה",
    "דוד",
    "שלמה",
    "שמואל",
    "יהושע",
    "דניאל",
    "אליהו",
    "נח",
    "שרה",
    "רות",
    "אסתר",
    "איוב",
    "יונה",
    "ישעיהו",
    "ירמיהו",
    "יחזקאל",
    "אנדריאס",
    "פיליפוס",
    "תומא",
    "מתתיהו",
    "יהודה",
    "שאול",
    "מלאך",
    "שרפים",
    "כרובים",
    "מלאכים",
    "נביא",
    "נביאים",
    "אור",
    "חיים",
    "אמונה",
    "ברית",
    "חסד",
    "שלום",
    "אמת",
    "תורה",
    "דבר",
    "רוח",
    "גאולה",
    "צלב",
    "דג",
    "מים",
    "לחם",
    "יין",
    "אבן",
    "דרך",
    "נר",
    "שמים",
    "לב",
    "חכמה",
    "תקווה",
    "אהבה",
    "צדק",
    "ברכה",
    "ירושלים",
    "גליל",
    "כנרת",
    "ירדן",
    "סיני",
    "ביתלחם",
    "נצרת",
    "ציון",
    "מקדש",
    "מנורה",
    "שופר",
    "מזבח",
    "ארון",
    "ספר",
    "מגילה",
  ],
};

export const PRELOADED_TRANSLATIONS = {
  hebrew_figures: {
    ישוע: { translation: "Jesus", pronunciation: "Yeshua" },
    יהוה: { translation: "YHWH", pronunciation: "YHWH" },
    רוחהקודש: { translation: "Holy Spirit", pronunciation: "Ruach HaKodesh" },
    פטרוס: { translation: "Peter", pronunciation: "Petros" },
    יוחנן: { translation: "John", pronunciation: "Yochanan" },
    יעקב: { translation: "James", pronunciation: "Ya'akov" },
    מרים: { translation: "Mary", pronunciation: "Miryam" },
    מיכאל: { translation: "Michael", pronunciation: "Mikha'el" },
    גבריאל: { translation: "Gabriel", pronunciation: "Gavri'el" },
    רפאל: { translation: "Raphael", pronunciation: "Rafa'el" },
    אברהם: { translation: "Abraham", pronunciation: "Avraham" },
    משה: { translation: "Moses", pronunciation: "Moshe" },
    דוד: { translation: "David", pronunciation: "David" },
    שרפים: { translation: "Seraphim", pronunciation: "Serafim" },
  },
  hebrew_sample: {
    שלום: { translation: "Peace", pronunciation: "Shalom" },
    חלום: { translation: "Dream", pronunciation: "Chalom" },
    עולם: { translation: "World", pronunciation: "Olam" },
    מלך: { translation: "King", pronunciation: "Melekh" },
    יום: { translation: "Day", pronunciation: "Yom" },
    לילה: { translation: "Night", pronunciation: "Lailah" },
  },
  hebrew_library: {
    ישוע: { translation: "Jesus", pronunciation: "Yeshua" },
    יהוה: { translation: "YHWH", pronunciation: "YHWH" },
    משיח: { translation: "Messiah", pronunciation: "Mashiach" },
    רוחהקודש: { translation: "Holy Spirit", pronunciation: "Ruach HaKodesh" },
    מרים: { translation: "Mary", pronunciation: "Miryam" },
    יוסף: { translation: "Joseph", pronunciation: "Yosef" },
    פטרוס: { translation: "Peter", pronunciation: "Petros" },
    יוחנן: { translation: "John", pronunciation: "Yochanan" },
    יעקב: { translation: "James", pronunciation: "Ya'akov" },
    מיכאל: { translation: "Michael", pronunciation: "Mikha'el" },
    גבריאל: { translation: "Gabriel", pronunciation: "Gavri'el" },
    רפאל: { translation: "Raphael", pronunciation: "Rafa'el" },
    אברהם: { translation: "Abraham", pronunciation: "Avraham" },
    יצחק: { translation: "Isaac", pronunciation: "Yitzchak" },
    משה: { translation: "Moses", pronunciation: "Moshe" },
    דוד: { translation: "David", pronunciation: "David" },
    שלמה: { translation: "Solomon", pronunciation: "Shlomo" },
    שמואל: { translation: "Samuel", pronunciation: "Shmuel" },
    יהושע: { translation: "Joshua", pronunciation: "Yehoshua" },
    דניאל: { translation: "Daniel", pronunciation: "Dani'el" },
    אליהו: { translation: "Elijah", pronunciation: "Eliyahu" },
    נח: { translation: "Noah", pronunciation: "Noach" },
    שרה: { translation: "Sarah", pronunciation: "Sarah" },
    רות: { translation: "Ruth", pronunciation: "Rut" },
    אסתר: { translation: "Esther", pronunciation: "Ester" },
    איוב: { translation: "Job", pronunciation: "Iyov" },
    יונה: { translation: "Jonah", pronunciation: "Yonah" },
    ישעיהו: { translation: "Isaiah", pronunciation: "Yeshayahu" },
    ירמיהו: { translation: "Jeremiah", pronunciation: "Yirmeyahu" },
    יחזקאל: { translation: "Ezekiel", pronunciation: "Yechezkel" },
    אנדריאס: { translation: "Andrew", pronunciation: "Andreas" },
    פיליפוס: { translation: "Philip", pronunciation: "Philippos" },
    תומא: { translation: "Thomas", pronunciation: "Toma" },
    מתתיהו: { translation: "Matthew", pronunciation: "Mattityahu" },
    יהודה: { translation: "Jude", pronunciation: "Yehudah" },
    שאול: { translation: "Paul", pronunciation: "Sha'ul" },
    מלאך: { translation: "Angel", pronunciation: "Malakh" },
    שרפים: { translation: "Seraphim", pronunciation: "Serafim" },
    כרובים: { translation: "Cherubim", pronunciation: "Keruvim" },
    מלאכים: { translation: "Angels", pronunciation: "Malakhim" },
    נביא: { translation: "Prophet", pronunciation: "Navi" },
    נביאים: { translation: "Prophets", pronunciation: "Nevi'im" },
    אור: { translation: "Light", pronunciation: "Or" },
    חיים: { translation: "Life", pronunciation: "Chayim" },
    אמונה: { translation: "Faith", pronunciation: "Emunah" },
    ברית: { translation: "Covenant", pronunciation: "Brit" },
    חסד: { translation: "Mercy", pronunciation: "Chesed" },
    שלום: { translation: "Peace", pronunciation: "Shalom" },
    אמת: { translation: "Truth", pronunciation: "Emet" },
    תורה: { translation: "Torah", pronunciation: "Torah" },
    דבר: { translation: "Word", pronunciation: "Davar" },
    רוח: { translation: "Spirit", pronunciation: "Ruach" },
    גאולה: { translation: "Redemption", pronunciation: "Geulah" },
    צלב: { translation: "Cross", pronunciation: "Tzlav" },
    דג: { translation: "Fish", pronunciation: "Dag" },
    מים: { translation: "Water", pronunciation: "Mayim" },
    לחם: { translation: "Bread", pronunciation: "Lechem" },
    יין: { translation: "Wine", pronunciation: "Yayin" },
    אבן: { translation: "Stone", pronunciation: "Even" },
    דרך: { translation: "Way", pronunciation: "Derekh" },
    נר: { translation: "Lamp", pronunciation: "Ner" },
    שמים: { translation: "Heavens", pronunciation: "Shamayim" },
    לב: { translation: "Heart", pronunciation: "Lev" },
    חכמה: { translation: "Wisdom", pronunciation: "Chokhmah" },
    תקווה: { translation: "Hope", pronunciation: "Tikvah" },
    אהבה: { translation: "Love", pronunciation: "Ahavah" },
    צדק: { translation: "Justice", pronunciation: "Tzedek" },
    ברכה: { translation: "Blessing", pronunciation: "Berakhah" },
    ירושלים: { translation: "Jerusalem", pronunciation: "Yerushalayim" },
    גליל: { translation: "Galilee", pronunciation: "Galil" },
    כנרת: { translation: "Kinneret", pronunciation: "Kinneret" },
    ירדן: { translation: "Jordan", pronunciation: "Yarden" },
    סיני: { translation: "Sinai", pronunciation: "Sinai" },
    ביתלחם: { translation: "Bethlehem", pronunciation: "Beit Lechem" },
    נצרת: { translation: "Nazareth", pronunciation: "Natzeret" },
    ציון: { translation: "Zion", pronunciation: "Tzion" },
    מקדש: { translation: "Temple", pronunciation: "Mikdash" },
    מנורה: { translation: "Menorah", pronunciation: "Menorah" },
    שופר: { translation: "Shofar", pronunciation: "Shofar" },
    מזבח: { translation: "Altar", pronunciation: "Mizbeach" },
    ארון: { translation: "Ark", pronunciation: "Aron" },
    ספר: { translation: "Book", pronunciation: "Sefer" },
    מגילה: { translation: "Scroll", pronunciation: "Megillah" },
  },
};

export const listNames = Object.keys(PRELOADED_LISTS);
